import "./globals.css";
import { Inter } from "next/font/google";
import { AppProvider } from "@/context/context";
import { QueryClientProvider } from "@tanstack/react-query";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AppProvider>
        <body className={inter.className}>{children}</body>
      </AppProvider>
    </html>
  );
}
