"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { AppProvider } from "@/context/context";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
const inter = Inter({ subsets: ["latin"] });

const queryClient = new QueryClient();

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

//<ReactQueryDevtools initialIsOpen={false} />;
export default function RootLayout({ children }) {
  return (
    <html lang="eng">
      <AppProvider>
        <QueryClientProvider client={queryClient}>
          <body className={inter.className}>{children}</body>
        </QueryClientProvider>
      </AppProvider>
    </html>
  );
}
